# An S*Interface must have at least one associated S*System of Access

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix interface: <http://incose.org/pwg/s-star/vocabulary/interface#>

select distinct ?if_l ?ok
where {
	?if a interface:Interface ; interface:hasIdentifier ?if_l .
	bind(exists { ?if interface:permitsSOA [ a interface:SystemOfAccess ] } as ?ok)
}
	
