# An S*Interface must have at least one associated S*System

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix interface: <http://incose.org/pwg/s-star/interface#>

select distinct ?if ?if_l ?ok
where {
	?if a interface:Interface ; rdfs:label ?if_l .
	bind(exists { [ a interface:System ] interface:providesInterface ?if . } as ?ok)
}
	