# An S*Interface must have at least one associated S*Input/Output

prefix interface: <http://incose.org/pwg/s-star/interface#>

select distinct ?if ?ok
where {
	?if a interface:Interface
	bind(exists { ?if interface:permitsInputOutput [ a interface:InputOutput ] } as ?ok)
}
	